#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# rebind escape
setxkbmap -option caps:escape

# Setup video outputs
function switch_displays() {
  internal="eDP-1"
  externals=("DP-1" "DP-2" "HDMI-1" "HDMI-2")
  connectedExternal=""

  for external in "${externals[@]}"
  do
    # echo "Testing external display $external"
    connected=$(xrandr | grep -e "^$external\sconnected" | wc -l)

    if [[ $connected -gt 0 ]] 
    then
      notify-send "External display $external is connected"
      connectedExternal=$external
    fi
  done

  disableExternals=" --output $internal --auto "

  for external in "${externals[@]}"
  do
    disableExternals+=" --output $external --off"
  done

  if [[ $connectedExternal ]]
  then
    echo "Enabling external screen $connectedExternal"
    notify-send "Enabling external screen $connectedExternal"
    bash -c "xrandr --output $connectedExternal --auto --output $internal --off"
  else
    echo "Enabling internal screen"
    notify-send "Enabling internal screen"
    bash -c "xrandr $disableExternals"
  fi
}

switch_displays

# end displays

#boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
fi

#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

#set background
if [ -x "$(command -v feh)" ]; then
  ~/.fehbg
fi

polybar -c $SCRIPTPATH/polybar.config main &> /dev/null &
