[font]
regular = "JetBrainsMono Nerd Font Mono"
bold = "JetBrainsMonoExtraBold Nerd Font"

[colors]
# black = "#1e2127"
# red = "#e06c75"
# green = "#98c379"
# yellow = "#d19a66"
# blue = "#61afef"
# magenta = "#c678dd"
# cyan = "#56b6c2"
# white = "#fff"

focus_fg = "#fff"
focus_bg = "#fff"
bg = "#1e2127"
fg = "#fff"
alert = "#e06c75"
accent = "#56b6c2"

[wm]
border_width = 1

