#!/bin/sh

cache_file=/tmp/external_display
if [ -f "$cache_file" ]; then
  # echo "read connected display from $cache_file"
  external=$(cat $cache_file)
else
  source ~/.config/scripts/displays
  external=$(connected_external)
  echo "$external" > $cache_file
fi

external=`echo $external | sed 's/ *$//g'`

scale=1

if [[ $external ]]
then
  scale=1 
else
  scale=1.2 
fi

echo "winit scale set to $scale"

WINIT_X11_SCALE_FACTOR=$scale alacritty

